---
- name: Deploy frontend and backend pods and services ok k8s
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    kubeconfig_path: "{{ lookup('env', 'KUBECONFIG') }}"
  tasks:
    - name: Deploy backtend pod
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file', 'backend-pod.yml') }}"

    - name: Deploy backtend service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file', 'backend-service.yml') }}"

    - name: Deploy frontend pod
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file', 'frontend-pod.yml') }}"

    - name: Deploy frontend service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file', 'frontend-service.yml') }}"

