---
- name: Deploy frontend and backend pods and services ok k8s
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    kubeconfig_path: "/root/.jenkins/workspace/terraform-eks-cluster/kubeconfig"
  tasks:
    - name: Deploy backtend pod
      shell: kubectl apply -f 'backend-pod.yml'
      register: status

    - debug: var=status
      # k8s:
      #   kubeconfig: "{{ kubeconfig_path }}"
      #   state: present
      #   definition: "{{ lookup('file', 'backend-pod.yml') }}"

    - name: Deploy backtend service
      shell: kubectl apply -f 'backend-service.yml'
      register: status

    - debug: var=status

    - name: Deploy frontend pod
      shell: kubectl apply -f 'frontend-pod.yml'
      register: status

    - debug: var=status

    - name: Deploy frontend service
      shell: kubectl apply -f 'frontend-service.yml'
      register: status

    - debug: var=status

