apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
  containers:
    - name: whiskerwag-frontend
      iamge: chinmaykulkarni19/whiskerwagg-frontend
      ports:
        - containerPort: 8000
